project:
  type: book
  output-dir: _book

book:
  title: Parallel Practical
  chapters:
    - index.qmd
    - ParallelPrac.qmd
  sidebar:
    border: true
    background: light
    position: right
  navbar:
    search: true
    background: light

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left



